<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<LangVersion>latest</LangVersion>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>gpt-text-generator-entities</PackageId>
	<Title>GPTTextGenerator.Entites</Title>
	<Authors>InanisPluvia</Authors>
	<PackageOutputPath>C:\Users\LordVT\Desktop\FinalQualifyingWork\src\csharp\NugetRepo</PackageOutputPath>
	<Version>1.1.18</Version>
	<Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
